#!/usr/bin/env node
import fs from 'node:fs'
import path from 'node:path'

const cwd = process.cwd()
const pkg = JSON.parse(fs.readFileSync(path.join(cwd, 'package.json'), 'utf8'))
const target = path.join(cwd, 'src', 'version.ts')
const banner = '// generated by scripts/inject-version.mjs — do not edit by hand\n'
fs.writeFileSync(target, `${banner}export const version = '${pkg.version}'\n`)
